### ISSUE TITLE
mpv?? !

### ISSUE THREAD

**Issue by OmiChrome** [sdaqo/anipy-gui#1]
![image](https://user-images.githubusercontent.com/108952834/195610919-4d4cb74a-74b5-42f0-a0e1-a713313cc864.png)
im getting this issue while install . maybe it can't  recogonise my mpv  even its on path

**Comment by sdaqo** [comment]
As you can see in the error mpv-2.dll is not in your path. Either you can look at the sample config, there you can get a link to download or deactivate the reuse mpv window config option

**Comment by sdaqo** [comment]
It doesn't run properly on windows, you can try downloading the mpv dll though.

**Comment by sdaqo** [comment]
[](url)

**Comment by OmiChrome** [comment]
> 

WHAT  do yuo mean?  i have my mpv  PATH  properly :(
